#!/bin/sh

swaybg -i $(find ~/media/Pictures/bg_images/. -type f | shuf -n1) -m fit &

while true; do
    sleep 600
    kill $(pidof swaybg)
    sleep 1
    swaybg -i $(find ~/media/Pictures/bg_images/. -type f | shuf -n1) -m fit & 
done
